Cluster:
  Name: tsb
  KopsClusterName: tsb.k8s.local
  NodeCount: 3
  NodeSize: m5.2xlarge
  AvailabilityZone: us-east-2a


Deployment:
  # for the namespaces that are created
  NamespacePrefix: "benchmarks-"

  # Parameters for each database:
  Timescale:
    StorageSize: "1000Gi"
  Influx:
    StorageSize: "1000Gi"


Benchmarking:
  # Parameters common to all databases, can be overriden in specific db's
  Common:
    InsertNumStreams:
    - 5
    - 10
    InsertSpanSeconds: 20000
    InsertSubsample: 1
    InsertTSJitter:
    - false
    - true
    Insert32Bit:
    - false
    - true
    SequentialReadParallelNum:
    - 1
    - 10
    SmallAggregationWindowSize: 1000000000
  PredictiveGrid:
    InsertBatchSize: 50000
  Timescale:
    InsertBatchSize: 100
  Influx:
    InsertBatchSize: 100

Endpoints:
  PredictiveGrid:
    CollectionPrefix: benchmarking
    Endpoint: btrdb-bootstrap.benchmarks-pg:4410
    APIKey: ""
    ReadBatchSize: 500
  Timescale:
    Password: supersecurepassword
    Endpoint: timescale.benchmarks-timescale:5432
    Database: postgres
    Username: postgres
  Influx:
    Endpoint: http://influx.benchmarks-influx:8086
