apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timescale 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: timescale
    spec:
      containers:
        - name: timescale
          image: timescale/timescaledb:latest-pg11 
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: timescale-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: timescaledb
      volumes:
        - name: timescaledb
          persistentVolumeClaim:
            claimName: timescale-pv-claim

